### ISSUE TITLE
无法获取当前ItemView

### ISSUE THREAD

**Issue by ChenJia-X** [wurensen/GraceViewPager#3]
ViewItemHolder为Private，无法通过继承获取mItemView。只能把整个库6个文件都复制进项目进行修改

**Comment by wurensen** [comment]
ViewItemHolder的设计仅仅就是为了持有映射关系。继承GracePagerAdapter的时候，ItemView的创建是由开发者提供的，所以开发者本身就可以拿到ItemView的引用。
