### ISSUE TITLE
不能设置padding那如何显示更多的页面和控制左右视图的显示比例呢

### ISSUE THREAD

**Issue by Yuphee** [wurensen/GraceViewPager#5]

**Comment by wurensen** [comment]
@Yuphee readme文档有说明，使用：gvp_pageHorizontalMinMargin/gvp_pageVerticalMinMargin分别控制水平/垂直的最小间距，实质上也是使用padding属性来达到显示多个页面的目的。至于控制左右视图的显示比例，你应该指的是动画吧，例如中间大，两边小的效果？这个要看你自己的需求，实现切换动画（继承GracePageTransformer来实现自己想要的效果）。
